import { defineStore } from "pinia";

export const useFriendStore = defineStore("friend", () => {
  const friends: Array = [
    {
      id: 1,
      title: "Ahmed Nasser",
      job: "JavaScript Developer",
      fr: "99",
      pro: "15",
      ar: "70",
      date: "Joined 02/10/2021",
      photo: "/images/friend-01.jpg",
    },
    {
      id: 2,
      title: "Omar Fathy",
      job: "Cloud Developer",
      fr: "30",
      pro: "11",
      ar: "12",
      date: "Joined 02/08/2020",
      photo: "/images/friend-02.jpg",
    },
    {
      id: 3,
      title: "Omar Ahmed",
      job: "Mobile Developer",
      fr: "80",
      pro: "20",
      ar: "18",
      date: "Joined 02/06/2020",
      photo: "/images/friend-03.jpg",
    },
    {
      id: 4,
      title: "Shady Nabil",
      job: "Back-End Developer",
      fr: "70",
      pro: "30",
      ar: "18",
      date: "Joined 28/06/2020",
      photo: "/images/friend-04.jpg",
    },
    {
      id: 5,
      title: "Mohamed Ibrahim",
      job: "Algorithm Developer",
      fr: "80",
      pro: "30",
      ar: "18",
      date: "Joined 28/08/2020",
      photo: "/images/friend-05.jpg",
    },
    {
      id: 6,
      title: "Hamza Hendawy",
      job: "Back-End Developer",
      fr: "70",
      pro: "60",
      ar: "18",
      date: "Joined 28/08/2020",
      photo: "/images/friend-04.jpg",
    },
    {
      id: 7,
      title: "Mahmoud",
      job: "Cloud Developer",
      fr: "20",
      pro: "60",
      ar: "18",
      date: "Joined 28/08/2020",
      photo: "/images/friend-02.jpg",
    },
    {
      id: 8,
      title: "Omar",
      job: "Mobile Developer",
      fr: "80",
      pro: "20",
      ar: "18",
      date: "Joined 02/06/2020",
      photo: "/images/friend-03.jpg",
    },
    {
      id: 9,
      title: "Gareeb Elshiekh",
      job: "Back-End Developer",
      fr: "70",
      pro: "30",
      ar: "18",
      date: "Joined 28/06/2020",
      photo: "/images/friend-04.jpg",
    },
    {
      id: 10,
      title: "lorem ipsuum",
      job: "Algorithm Developer",
      fr: "80",
      pro: "30",
      ar: "18",
      date: "Joined 28/08/2020",
      photo: "/images/friend-05.jpg",
    },
  ];
  return {
    friends,
  };
});
